version: 2

sources:
  - name: ga4
    description: "GA4 public sample ecommerce dataset"
    database: bigquery-public-data
    schema: ga4_obfuscated_sample_ecommerce
    tables:
      - name: events
        identifier: events_*
        description: "Daily GA4 events tables (wildcard)"
